[build]
  command = "npm run build"
  publish = ".next"

# Ensure correct Node.js version on Netlify
[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyAGwzDlJp1E56x69KeyhWibHtvoTNWMQ4c"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "campanion-cursor.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "campanion-cursor"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "campanion-cursor.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "22851781795"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:22851781795:web:PLACEHOLDER"

[[plugins]]
  package = "@netlify/plugin-nextjs"


